services:
  umi-admin-server:
    build:
      context: .
    image: "${IMAGE_NAME}"  # 使用环境变量
    container_name: "${CONTAINER_NAME}"  # 使用环境变量
    environment:
      - NODE_ENV=production
      - NEST_MYSQL_HOST=mysql
      - NEST_REDIS_PORT=redis
    ports:
      - "3000:3000"
    restart: always
    networks:
      - coderzzx_network
    volumes:
      - ./.env:/app/.env.production

networks:
  coderzzx_network:
    external: true
